CC=gcc
CFLAGS=-Wall -std=c17

.PHONY: all santa_claus_problem clean

all: santa_claus_problem

santa_claus_problem: santa_claus_problem.c
	$(CC) $(CFLAGS) santa_claus_problem.c -o santa_claus_problem

clean:
	rm -f santa_claus_problem