CC=gcc
CFLAGS=-Wall -std=c17

.PHONY: all zad1 zad2 clean

all: zad1 zad2

zad1: zad1.c 
	$(CC) $(CFLAGS) -o zadanie1 zad1.c

zad2: zad2.c
	$(CC) $(CFLAGS) -o zadanie2 zad2.c

clean:
	rm zadanie1 zadanie2