CC=gcc
CFLAGS=-Wall -std=c17

.PHONY: all zad1 zad2_1 zad2_2 clean

all: zad1 zad2_1 zad2_2

zad1: zad1.c
	$(CC) $(CFLAGS) -o zad1 zad1.c

zad2_1: zad2_1.c
	$(CC) $(CFLAGS) -o zad2_1 zad2_1.c

zad2_2: zad2_2.c
	$(CC) $(CFLAGS) -o zad2_2 zad2_2.c

clean: 
	rm zad1 zad2_1 zad2_2